name: Gatsby Build

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - master

jobs:
  # dependencies:
  #   name: "Dependencies"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     #- run: docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
  #     #- run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/dependencies:latest || true
  #     - name: Docker Build and Push
  #       uses: docker/build-push-action@v1.1.0
  #       with:
  #         cache_froms: andrioid/andri.dk/dependencies:latest
  #         repository: andrioid/andri.dk/dependencies
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #         registry: docker.pkg.github.com
  #         target: dependencies
  #         tag_with_sha: true
  #         tag_with_ref: true
  #         build_args: BUILDKIT_INLINE_CACHE=1

  deps:
    name: "Dependencies"
    #needs: [dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/dependencies:latest || true
      - run: docker build . --target dependencies -t dependencies --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/dependencies:latest --build-arg BUILDKIT_INLINE_CACHE=1
      - run: docker tag dependencies docker.pkg.github.com/$GITHUB_REPOSITORY/dependencies
      - run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/dependencies:latest
  site:
    name: "Gatsby"
    needs: [deps]
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/andrioid/andri.dk/dependencies:latest
      volumes:
        - .:/home/node/app
    steps:
      - run: ls -alh
      - run: npm run build
